### PR TITLE
[WIP] Add experiment that simulates AWS Az being down

### PR DESCRIPTION
**Pull request by damienomurchu**
## What

https://issues.redhat.com/browse/MGDSTRM-579
Add chaos experiment that simulates az being down

## Why

To ensure resiliency of our service we need to evaluate what impact that an availability zone being down will have.

## How

- Add new litmus-go experiment for az-down
- create dummy ACLs with deny all traffic policies
- assign ACLs to subnets of az under test
- revert ACL changes after experiment concludes

### CODE REVIEW

**Comment by damienomurchu** [comment]
Premature PR

**Comment by ksatchit** [comment]
Hi @damienomurchu. Thank you for contributing this experiment 👍 .. if you'd like to open a draft PR and want to discuss - please feel free to do that!

**Comment by damienomurchu** [comment]
Thanks @ksatchit :+1: 

I'm just iterating and testing this on my fork, but happy to open a draft pr once its a bit more advanced.

**Comment by damienomurchu** [comment]
@ksatchit I've opened a draft PR here by the way, #230 

Trying to test it locally with okteto but I may be overlooking something and raised an issue here (#229 ) if you had any thoughts/ pointers

**Pull request closed without merging**
