### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
**What this PR does / why we need it**:
This PR adds link to the `License` file in the Readme for easy access. 

Signed-off-by: Saptarshi Sarkar <saptarshi.programmer@gmail.com>

### CODE REVIEW

**Comment by neelanjan00** [comment]
Thanks for the PR @SaptarshiSarkar12! The license in the readme indicated open-source License Scanning and vulnerability status report delivered by FOSSA scan. You may improve the heading for the same, I guess.

**Comment by SaptarshiSarkar12** [comment]
Welcome @neelanjan00 . I have added a heading for license scanning and vulnerability check section. You can check it out.


Signed-off-by: Saptarshi Sarkar <saptarshi.programmer@gmail.com>

**Review by neelanjan00 — APPROVED** [review]

**Comment by neelanjan00** [comment]
The DCO is failing, can you fix it? The steps for it are given in the [details](https://github.com/litmuschaos/litmus-go/pull/559/checks?check_run_id=8447300352).

**Comment by SaptarshiSarkar12** [comment]
> The DCO is failing, can you fix it? The steps for it are given in the [details](https://github.com/litmuschaos/litmus-go/pull/559/checks?check_run_id=8447300352).

@neelanjan00 I have successfully fixed it. Do check it out at the earliest.

**Comment by SaptarshiSarkar12** [comment]
@neelanjan00 @ispeakc0de  @uditgaurav @avaakash Please anyone merge this PR if it is ready to be merged.

**Review by ispeakc0de — APPROVED** [review]

**Review by neelanjan00 — APPROVED** [review]

**Comment by SaptarshiSarkar12** [comment]
Thanks @ispeakc0de

**Pull request merged**
