### PR TITLE
Fix helper pod issue for Kubelet Experiment

### PR DESCRIPTION
**Pull request by tanmaypandey7**
**What this PR does / why we need it**: To fix kubelet service kill experiment error.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
https://github.com/litmuschaos/litmus-go/issues/536

**Special notes for your reviewer**:

**Checklist:**
-   [ ] Fixes #<issue number>
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

### CODE REVIEW

**Review by ispeakc0de — DISMISSED** [review]

**Review by neelanjan00 — DISMISSED** [review]

**Comment by neelanjan00** [comment]
@ispeakc0de can we merge this?

**Comment by neelanjan00** [comment]
@tanmaypandey7 the gofmt CI check is failing, can you PTAL?

**Comment by tanmaypandey7** [comment]
@neelanjan00 should pass now.

**Review by neelanjan00 — APPROVED** [review]

**Comment by tanmaypandey7** [comment]
@ispeakc0de please approve it.

**Review by ispeakc0de — APPROVED** [review]

**Pull request merged**
