### PR TITLE
Add support to specify network chaos targets as hostnames

### PR DESCRIPTION
**Pull request by piyush0609**

### CODE REVIEW

**Comment by ispeakc0de** [comment]
Thanks for the PR @piyush0609 

One question, Is the IP addresses passed inside `TARGET_IPs` and whatever we derive from `TARGET_HOSTS` can be same?

If yes then we are not overriding them before passing with the "--target" flag. Not sure if Pumba is handling duplicate `target` IP addr case or not.

**Comment by piyush0609** [comment]
> Thanks for the PR @piyush0609
> 
> One question, Is the IP addresses passed inside `TARGET_IPs` and whatever we derive from `TARGET_HOSTS` can be same?
> 
> If yes then we are not overriding them before passing with the `--target` flag. Not sure if Pumba is handling duplicate `target` IP addr case or not.

@ispeakc0de i will test it with pumba but the assumption is even if the there are two similar targets pumba should handle it internally when it creates `tc` aka traffic control rules. i will test this and let you know

**Comment by ksatchit** [comment]
@piyush0609 , we tested this locally & found it to be working when the same target's details are provided both as IP & hostname (service name). This was seen to work consistently for in-cluster resources. We did find some inconsistent behaviour (works sometimes, and doesn't at other) when using public IPs that may resolve to more than 1 IP internally (say, google.com) - but this is something we can look into after taking these changes. 

Thanks for this contribution!!

**Comment by piyush0609** [comment]
> @piyush0609 , we tested this locally & found it to be working when the same target's details are provided both as IP & hostname (service name), as well as other cases where both the TARGET_IPs & TARGET_HOSTs ENVs are populated w/ different targets. This was seen to work consistently for in-cluster resources. We did find some inconsistent behavior (works sometimes, and doesn't at other) when using public IPs that may resolve to more than 1 IP internally (say, google.com) - but this is something we can look into after taking these changes.
> 
> Thanks for this contribution!!

Thanks @ksatchit . I also tested this locally. Giving same IPs twice doesn't increase the latency by two times. Pumba seems to manage this internally. The inconsistent behavior you mentioned is something which is at the dns level. For internal AWS load balancers the feature seems to be working fine.

**Pull request merged**
