### PR TITLE
Add DockerSocket to network experiments && remove chmod 777

### PR DESCRIPTION
**Pull request by Vr00mm**
Signed-off-by: Rémi ZIOLKOWSKI <remi.ziolkowski-ext@pole-emploi.fr>

**What this PR does / why we need it**:
Its remove the huge security issue that do chmod 777 on your host docker sock
Is the read/write mount no enought ?

Its give the DOCKER_HOST variable to pumba ( iam using docker but my sock is not default path)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
https://github.com/litmuschaos/litmus/issues/3147

**Special notes for your reviewer**:

**Checklist:**
-   [x] Fixes https://github.com/litmuschaos/litmus/issues/3147
-   [ ] PR messages has document related information
-   [ ] Labelled this PR & related issue with `breaking-changes` tag
-   [ ] PR messages has breaking changes related information
-   [ ] Labelled this PR & related issue with `requires-upgrade` tag
-   [ ] PR messages has upgrade related information
-   [ ] Commit has unit tests
-   [ ] Commit has integration tests
-   [ ] E2E run Required for the changes

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks @Vr00mm - there are some parallel efforts going on to fix this for the pumba lib - as you might know, the native litmus lib doesn't perform this step/provide 777 permissions.  We will get back on this PR shortly.

**Comment by Vr00mm** [comment]
My cluster security policy disable privileged containers (:
I cant use the litmus lib then ):

Well i got luck on my test and my containers proc on the already 777 socket k8s node...
I reverted permissions and then its not work anymore..

At least, i can start the test on the good socket.
Ill try things arround securityContext.fsGroup or securityContext.runAsGroup awaiting more informations :)

See you later

**Comment by Vr00mm** [comment]
Or what about dind rootless ?
https://github.com/docker-library/docker/blob/master/Dockerfile-dind-rootless.template
I'll try thinks today, night help :)

**Comment by Vr00mm** [comment]
I did this and this seem working:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: experiment-job
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: 2.0.0
    chaosUID: e1719810-7081-4a8b-a142-d31ec6dd9fa6
    name: pod-network-latency
  name: pod-network-latency-v2qdjq
  namespace: oi137-litmus
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: experiment-job
        app.kubernetes.io/part-of: litmus
        app.kubernetes.io/version: 2.0.0
        chaosUID: e1719810-7081-4a8b-a142-d31ec6dd9fa6
        job-name: pod-network-latency-v2qdjq
        name: pod-network-latency
      name: pod-network-latency-v2qdjq
      namespace: oi137-litmus
    spec:
      containers:
      - args:
        - -c
        - ./experiments -name pod-network-latency
        command:
        - /bin/bash
        env:
        - name: SOCKET_PATH
          value: /var/vcap/sys/run/docker/docker.sock
        - name: STATUS_CHECK_TIMEOUT
          value: "180"
        - name: CHAOS_UID
          value: e1719810-7081-4a8b-a142-d31ec6dd9fa6
        - name: TERMINATION_GRACE_PERIOD_SECONDS
          value: "0"
        - name: LIB_IMAGE
          value: litmuschaos/go-runner:2.0.0-RC1
        - name: CONTAINER_RUNTIME
          value: docker
        - name: APP_KIND
          value: deployment
        - name: LIB_IMAGE_PULL_POLICY
          value: Always
        - name: APP_NAMESPACE
          value: litmus
        - name: NETWORK_LATENCY
          value: "2000"
        - name: RAMP_TIME
        - name: LIB
          value: pumba
        - name: SEQUENCE
          value: parallel
        - name: CHAOSENGINE
          value: pod-network-latencydkvtg
        - name: CHAOS_NAMESPACE
          value: oi137-litmus
        - name: PODS_AFFECTED_PERC
        - name: DESTINATION_IPS
        - name: DESTINATION_HOSTS
        - name: ANNOTATION_KEY
          value: litmuschaos.io/chaos
        - name: TC_IMAGE
          value: gaiadocker/iproute2
        - name: ANNOTATION_CHECK
          value: "false"
        - name: NETWORK_INTERFACE
          value: eth0
        - name: TOTAL_CHAOS_DURATION
          value: "60"
        - name: JOB_CLEANUP_POLICY
          value: retain
        - name: APP_LABEL
          value: app.kubernetes.io/name=load-balancer-example
        - name: EXPERIMENT_NAME
          value: pod-network-latency
        - name: TARGET_CONTAINER
        - name: STATUS_CHECK_DELAY
          value: "2"
        - name: TARGET_PODS
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: vr00mm/go-runner:0.2.1
        imagePullPolicy: Always
        name: pod-network-latency-v2qdjq
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: litmus-admin
      serviceAccountName: litmus-admin
      terminationGracePeriodSeconds: 30
```

From where i can change the image to use for more tests from portal ?

**Comment by Vr00mm** [comment]
my indent is ugly, i redo

**Comment by RobinSegura** [comment]
Hi ! 
Are we OK on this one ? 
could we check all of the following boxes ? Checklist:
- [ ]  document related information
- [ ] Labelled this PR & related issue with breaking-changes tag
- [ ] PR messages has breaking changes related information
- [ ] Labelled this PR & related issue with requires-upgrade tag
- [ ] PR messages has upgrade related information
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] E2E run Required for the changes

**Comment by Vr00mm** [comment]
Here is the result:
green

The last job is failled cause i did a fat ugly sed in my chaos-hub to change the default lib and its changed this one too :)
The manifest i used:
```yaml
kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: test-template-1629366027
  namespace: oi137-litmus
  creationTimestamp: null
  labels:
    cluster_id: 25114a35-a1ef-4cfa-8983-b683ab49b736
    subject: test-template_oi137-litmus
    workflow_id: 5ab33eba-3dcc-44f1-9f47-1fb8f0307ab0
    workflows.argoproj.io/controller-instanceid: 25114a35-a1ef-4cfa-8983-b683ab49b736
spec:
  templates:
    - name: custom-chaos
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: container-kill
            template: container-kill
            arguments: {}
        - - name: pod-network-loss
            template: pod-network-loss
            arguments: {}
        - - name: pod-network-latency
            template: pod-network-latency
            arguments: {}
        - - name: pod-delete
            template: pod-delete
            arguments: {}
    - name: install-chaos-experiments
      arguments: {}
      inputs:
        artifacts:
          - name: container-kill
            path: /tmp/container-kill.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Kills a container belonging to an application pod 
                kind: ChaosExperiment

                metadata:
                  name: container-kill
                  labels:
                    name: container-kill
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - apps
                          - batch
                          - apps.openshift.io
                          - argoproj.io
                          - litmuschaos.io
                        resources:
                          - jobs
                          - pods
                          - pods/log
                          - events
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - update
                          - patch
                          - delete
                          - deletecollection
                    image: vr00mm/go-runner:0.2.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name container-kill
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: pumba
                      - name: TARGET_PODS
                        value: ""
                      - name: CHAOS_INTERVAL
                        value: "10"
                      - name: SIGNAL
                        value: SIGKILL
                      - name: SOCKET_PATH
                        value: /var/vcap/sys/run/docker/docker.sock
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: TOTAL_CHAOS_DURATION
                        value: "20"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB_IMAGE
                        value: vr00mm/go-runner:0.2.1
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: container-kill
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: latest
          - name: pod-network-loss
            path: /tmp/pod-network-loss.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Injects network packet loss on pods belonging to an app deployment
                kind: ChaosExperiment

                metadata:
                  name: pod-network-loss
                  labels:
                    name: pod-network-loss
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - batch
                          - apps
                          - apps.openshift.io
                          - argoproj.io
                          - litmuschaos.io
                        resources:
                          - jobs
                          - pods
                          - pods/log
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - events
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - get
                          - list
                          - patch
                          - create
                          - update
                          - delete
                          - deletecollection
                    image: vr00mm/go-runner:0.2.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-network-loss
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: LIB_IMAGE
                        value: vr00mm/go-runner:0.2.1
                      - name: NETWORK_INTERFACE
                        value: eth0
                      - name: TC_IMAGE
                        value: gaiadocker/iproute2
                      - name: NETWORK_PACKET_LOSS_PERCENTAGE
                        value: "100"
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: pumba
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: DESTINATION_IPS
                        value: ""
                      - name: DESTINATION_HOSTS
                        value: ""
                      - name: SOCKET_PATH
                        value: /var/vcap/sys/run/docker/docker.sock
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-network-loss
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: latest
          - name: pod-network-latency
            path: /tmp/pod-network-latency.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Injects network latency on pods belonging to an app deployment
                kind: ChaosExperiment

                metadata:
                  name: pod-network-latency
                  labels:
                    name: pod-network-latency
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - batch
                          - apps
                          - apps.openshift.io
                          - argoproj.io
                          - litmuschaos.io
                        resources:
                          - jobs
                          - pods
                          - pods/log
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - events
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                          - deletecollection
                    image: vr00mm/go-runner:0.2.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-network-latency
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: NETWORK_INTERFACE
                        value: eth0
                      - name: LIB_IMAGE
                        value: vr00mm/go-runner:0.2.1
                      - name: TC_IMAGE
                        value: gaiadocker/iproute2
                      - name: NETWORK_LATENCY
                        value: "2000"
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: LIB
                        value: pumba
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: DESTINATION_IPS
                        value: ""
                      - name: DESTINATION_HOSTS
                        value: ""
                      - name: SOCKET_PATH
                        value: /var/vcap/sys/run/docker/docker.sock
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-network-latency
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: latest
          - name: pod-delete
            path: /tmp/pod-delete.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Deletes a pod belonging to a deployment/statefulset/daemonset
                kind: ChaosExperiment

                metadata:
                  name: pod-delete
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                          - apps
                          - apps.openshift.io
                          - argoproj.io
                          - batch
                          - litmuschaos.io
                        resources:
                          - deployments
                          - jobs
                          - pods
                          - pods/log
                          - replicationcontrollers
                          - deployments
                          - statefulsets
                          - daemonsets
                          - replicasets
                          - deploymentconfigs
                          - rollouts
                          - pods/exec
                          - events
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                          - deletecollection
                    image: vr00mm/go-runner:0.2.1
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-delete
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "15"
                      - name: RAMP_TIME
                        value: ""
                      - name: FORCE
                        value: "true"
                      - name: CHAOS_INTERVAL
                        value: "5"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB
                        value: pumba
                      - name: TARGET_PODS
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: latest
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/container-kill.yaml -n
            {{workflow.parameters.adminModeNamespace}} | kubectl apply -f
            /tmp/pod-network-loss.yaml -n
            {{workflow.parameters.adminModeNamespace}} | kubectl apply -f
            /tmp/pod-network-latency.yaml -n
            {{workflow.parameters.adminModeNamespace}} | kubectl apply -f
            /tmp/pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}}
            |  sleep 30
        resources: {}
    - name: container-kill
      arguments: {}
      inputs:
        artifacts:
          - name: container-kill
            path: /tmp/chaosengine-container-kill.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: container-kill
                  labels:
                    instance_id: 4efa6851-10f5-4ada-b3be-3338e0140391
                    context: container-kill_oi137-litmus
                    workflow_name: test-template-1629366027
                spec:
                  engineState: active
                  appinfo:
                    appns: litmus
                    applabel: app.kubernetes.io/name=load-balancer-example
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: container-kill
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "20"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/vcap/sys/run/docker/docker.sock
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: TARGET_CONTAINER
                              value: ""
                        probe: []
                  annotationCheck: "false"
                  jobCleanUpPolicy: retain
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-container-kill.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: pod-network-loss
      arguments: {}
      inputs:
        artifacts:
          - name: pod-network-loss
            path: /tmp/chaosengine-pod-network-loss.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-network-loss
                  labels:
                    instance_id: 894b7581-0886-4cd9-bd87-375b6a114414
                    context: pod-network-loss_oi137-litmus
                    workflow_name: test-template-1629366027
                spec:
                  engineState: active
                  appinfo:
                    appns: litmus
                    applabel: app.kubernetes.io/name=load-balancer-example
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-network-loss
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: NETWORK_PACKET_LOSS_PERCENTAGE
                              value: "100"
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/vcap/sys/run/docker/docker.sock
                            - name: PODS_AFFECTED_PERC
                              value: ""
                        probe: []
                  annotationCheck: "false"
                  jobCleanUpPolicy: retain
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-network-loss.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: pod-network-latency
      arguments: {}
      inputs:
        artifacts:
          - name: pod-network-latency
            path: /tmp/chaosengine-pod-network-latency.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-network-latency
                  labels:
                    instance_id: 117988a3-6277-43e6-badb-73e0675a97f9
                    context: pod-network-latency_oi137-litmus
                    workflow_name: test-template-1629366027
                spec:
                  engineState: active
                  appinfo:
                    appns: litmus
                    applabel: app.kubernetes.io/name=load-balancer-example
                    appkind: deployment
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-network-latency
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: NETWORK_LATENCY
                              value: "2000"
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/vcap/sys/run/docker/docker.sock
                            - name: PODS_AFFECTED_PERC
                              value: ""
                        probe: []
                  annotationCheck: "false"
                  jobCleanUpPolicy: retain
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-network-latency.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: pod-delete
      arguments: {}
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine-pod-delete.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-delete
                  labels:
                    instance_id: 043c34db-e39f-4528-a419-f6e98904d7cf
                    context: pod-delete_oi137-litmus
                    workflow_name: test-template-1629366027
                spec:
                  appinfo:
                    appns: litmus
                    applabel: app.kubernetes.io/name=load-balancer-example
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: ""
                        probe: []
                  annotationCheck: "false"
                  jobCleanUpPolicy: retain
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine-pod-delete.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: custom-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: oi137-litmus
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  ? startedAt
  ? finishedAt
```
Litmus event:
litmus-event

Target event:
target-event

**Review by ispeakc0de — DISMISSED** [review]

**Comment by Vr00mm** [comment]
Ill check for the Build / pre-checks (pull_request) Failled.
@ispeakc0de Is the Ipv6 listen disabled in nginx conf thats deployed ?

**Review by ispeakc0de — APPROVED** [review]

**Review by ksatchit — APPROVED** [review]

**Comment by ksatchit** [comment]
Thanks for the results @Vr00mm

**Pull request merged**
